CREATE TABLE roles (name VARCHAR(20) PRIMARY KEY, description VARCHAR(255) NOT NULL);
INSERT INTO roles VALUES ('STUDENT','Completes networking assignments'),('FACULTY','Manages assignments and grades submissions'),('ADMIN','Manages the platform');
ALTER TABLE users ADD CONSTRAINT users_role_fk FOREIGN KEY (role) REFERENCES roles(name);
ALTER TABLE users ADD COLUMN tokens_valid_after TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN auth_version UUID NOT NULL DEFAULT gen_random_uuid();
CREATE UNIQUE INDEX users_normalized_email_idx ON users(lower(email));
ALTER TABLE assignments ADD COLUMN slug VARCHAR(255) UNIQUE;
ALTER TABLE assignments ADD COLUMN metadata JSONB NOT NULL DEFAULT '{}';
ALTER TABLE assignments ADD COLUMN deadline TIMESTAMPTZ;
ALTER TABLE assignments ADD CONSTRAINT assignment_status_check CHECK (status IN ('ACTIVE','INACTIVE'));
ALTER TABLE assignment_attempts ADD COLUMN solution TEXT NOT NULL DEFAULT '';
ALTER TABLE assignment_attempts ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE assignment_attempts ADD CONSTRAINT attempt_status_check CHECK (status IN ('STARTING','RUNNING','TESTED','FAILED','SUBMITTED'));
ALTER TABLE submissions ADD CONSTRAINT unique_submission_attempt UNIQUE(attempt_id);
ALTER TABLE submissions ADD CONSTRAINT submission_status_check CHECK (status IN ('SUBMITTED','REVIEWED','RETURNED','REJECTED'));
CREATE TABLE assignment_test_cases (
 id UUID PRIMARY KEY, assignment_id UUID NOT NULL REFERENCES assignments(id),
 name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, weight INTEGER NOT NULL CHECK(weight BETWEEN 1 AND 100),
 enabled BOOLEAN NOT NULL DEFAULT TRUE, configuration JSONB NOT NULL,
 UNIQUE(assignment_id,name)
);
CREATE TABLE submission_test_results (
 id UUID PRIMARY KEY, attempt_id UUID NOT NULL REFERENCES assignment_attempts(id),
 submission_id UUID REFERENCES submissions(id), test_case_id UUID NOT NULL REFERENCES assignment_test_cases(id),
 passed BOOLEAN NOT NULL, output TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(attempt_id,test_case_id)
);
CREATE TABLE faculty_reviews (
 id UUID PRIMARY KEY, submission_id UUID NOT NULL REFERENCES submissions(id), faculty_id UUID NOT NULL REFERENCES users(id),
 grade NUMERIC(5,2) CHECK(grade BETWEEN 0 AND 100), feedback TEXT NOT NULL, status VARCHAR(255) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE network_servers (
 id UUID PRIMARY KEY, name VARCHAR(255) NOT NULL, service VARCHAR(255) NOT NULL UNIQUE, address VARCHAR(255) NOT NULL,
 port INTEGER NOT NULL CHECK(port BETWEEN 0 AND 65535), protocol VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL,
 last_heartbeat TIMESTAMPTZ
);
CREATE TABLE network_sessions (
 id UUID PRIMARY KEY, attempt_id UUID NOT NULL UNIQUE REFERENCES assignment_attempts(id),
 server_id UUID NOT NULL REFERENCES network_servers(id), status VARCHAR(255) NOT NULL,
 started_at TIMESTAMPTZ NOT NULL DEFAULT now(), ended_at TIMESTAMPTZ
);
CREATE TABLE audit_logs (
 id UUID PRIMARY KEY, actor_id UUID REFERENCES users(id), action VARCHAR(255) NOT NULL,
 resource VARCHAR(255) NOT NULL, details TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX cases_assignment_idx ON assignment_test_cases(assignment_id);
CREATE INDEX results_submission_idx ON submission_test_results(submission_id);
CREATE INDEX reviews_submission_idx ON faculty_reviews(submission_id);
CREATE INDEX submissions_student_idx ON submissions(student_id,submitted_at);
CREATE INDEX attempts_started_idx ON assignment_attempts(started_at);
CREATE INDEX audit_created_idx ON audit_logs(created_at);
INSERT INTO assignments(id,title,description,protocol,difficulty,status,slug,requirements,concepts,metadata) VALUES ('00000000-0000-4000-8000-000000000001','TCP Chat Client','Build a college messaging client with a username handshake, multiple messages and graceful disconnection.','TCP','EASY','ACTIVE','tcp-chat','["Handshake with USER <name>","Send MSG <text> and read each reply","QUIT gracefully; catch connection failures"]'::jsonb,'["TCP","Sockets","Connection lifecycle"]'::jsonb,'{"objective":"Build a college messaging client with a username handshake, multiple messages and graceful disconnection.","constraints":["JavaScript solve(input) runs in an isolated interpreter","15 seconds per test, 16 MiB memory, 60 network operations","Only the supplied LabLink network services are accessible"],"instructions":["Read the protocol and capability API","Implement solve(input) for every test input","Run to inspect output, then Test before submitting"],"expectedBehavior":"Return {welcome, replies, closed:true} for input.username/messages. On input.service=''offline'', return {error:true}. Treat QUIT as a server disconnect and close your socket.","starterCode":"function solve(input) {\n  // Implement the requirements using the capability API below.\n  print(input);\n  return {};\n}","serverRequirement":"Controlled TCP tcp-chat service","capabilityApi":"tcp.connect(''chat''|''file''|''search''|''offline''), tcp.send(id,line), tcp.read(id), tcp.close(id); udp.exchange(updates); http.request(path,method); http.probe(name); dns.lookup(name); save(name,content); sha256(content); print(value). All calls are synchronous inside the isolated interpreter."}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000001','Handshake and message','tcp-chat',35,'{"input":{"service":"chat","username":"Ada","messages":["Hello"]}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000001','Multiple messages and disconnect','tcp-chat',40,'{"input":{"service":"chat","username":"Lin","messages":["first","second","third"]}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000001','Connection failure','tcp-chat',25,'{"input":{"service":"offline","username":"Test","messages":[]}}'::jsonb);
INSERT INTO network_servers(id,name,service,address,port,protocol,status) VALUES(gen_random_uuid(),'TCP Chat Client service','chat','127.0.0.1',0,'TCP','ACTIVE');
INSERT INTO assignments(id,title,description,protocol,difficulty,status,slug,requirements,concepts,metadata) VALUES ('00000000-0000-4000-8000-000000000002','Reliable File Transfer','Receive, save and verify a requested file through a real TCP stream.','TCP','MEDIUM','ACTIVE','file-transfer','["Send GET <filename>","Parse JSON header and all DATA chunks until END","Save the reconstructed file and verify SHA-256","Handle missing and interrupted transfers"]'::jsonb,'["Streams","Buffering","Integrity"]'::jsonb,'{"objective":"Receive, save and verify a requested file through a real TCP stream.","constraints":["JavaScript solve(input) runs in an isolated interpreter","15 seconds per test, 16 MiB memory, 60 network operations","Only the supplied LabLink network services are accessible"],"instructions":["Read the protocol and capability API","Implement solve(input) for every test input","Run to inspect output, then Test before submitting"],"expectedBehavior":"Server lines: {name,bytes,sha256}, DATA <base64>, END. Errors: ERROR NOT_FOUND. An interrupted transfer closes before END. Return {name,content,sha256,saved:true}; errors {error:true}. Use save(name,content) and sha256(content).","starterCode":"function solve(input) {\n  // Implement the requirements using the capability API below.\n  print(input);\n  return {};\n}","serverRequirement":"Controlled TCP file-transfer service","capabilityApi":"tcp.connect(''chat''|''file''|''search''|''offline''), tcp.send(id,line), tcp.read(id), tcp.close(id); udp.exchange(updates); http.request(path,method); http.probe(name); dns.lookup(name); save(name,content); sha256(content); print(value). All calls are synchronous inside the isolated interpreter."}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000002','Complete small file','file-transfer',30,'{"input":{"filename":"welcome.txt"}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000002','Stream reconstruction and integrity','file-transfer',40,'{"input":{"filename":"networks.txt"}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000002','Missing file','file-transfer',15,'{"input":{"filename":"missing.txt"}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000002','Interrupted transfer','file-transfer',15,'{"input":{"filename":"interrupted.txt"}}'::jsonb);
INSERT INTO network_servers(id,name,service,address,port,protocol,status) VALUES(gen_random_uuid(),'Reliable File Transfer service','file','127.0.0.1',0,'TCP','ACTIVE');
INSERT INTO assignments(id,title,description,protocol,difficulty,status,slug,requirements,concepts,metadata) VALUES ('00000000-0000-4000-8000-000000000003','UDP Multiplayer Position & Telemetry System','Send player coordinates and process broadcast updates while rejecting stale packets.','UDP','MEDIUM','ACTIVE','udp-telemetry','["Send actual UDP datagrams using udp.exchange","Track positions for every player","Keep only the highest sequence for each player"]'::jsonb,'["Datagrams","Packet loss","Sequence numbers"]'::jsonb,'{"objective":"Send player coordinates and process broadcast updates while rejecting stale packets.","constraints":["JavaScript solve(input) runs in an isolated interpreter","15 seconds per test, 16 MiB memory, 60 network operations","Only the supplied LabLink network services are accessible"],"instructions":["Read the protocol and capability API","Implement solve(input) for every test input","Run to inspect output, then Test before submitting"],"expectedBehavior":"Call udp.exchange(input.updates) once. It returns received datagrams including broadcasts and an intentionally stale packet. Return {positions:{player:{x,y,seq}}}; use sequence comparison, never arrival order.","starterCode":"function solve(input) {\n  // Implement the requirements using the capability API below.\n  print(input);\n  return {};\n}","serverRequirement":"Controlled UDP udp-telemetry service","capabilityApi":"tcp.connect(''chat''|''file''|''search''|''offline''), tcp.send(id,line), tcp.read(id), tcp.close(id); udp.exchange(updates); http.request(path,method); http.probe(name); dns.lookup(name); save(name,content); sha256(content); print(value). All calls are synchronous inside the isolated interpreter."}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000003','Position exchange','udp-telemetry',30,'{"input":{"updates":[{"player":"alice","x":2,"y":3,"seq":1}]}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000003','Multiple players','udp-telemetry',30,'{"input":{"updates":[{"player":"alice","x":4,"y":5,"seq":2},{"player":"bob","x":7,"y":8,"seq":1}]}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000003','Out of order updates','udp-telemetry',40,'{"input":{"updates":[{"player":"alice","x":8,"y":9,"seq":5},{"player":"alice","x":0,"y":0,"seq":2},{"player":"bob","x":3,"y":2,"seq":3}]}}'::jsonb);
INSERT INTO network_servers(id,name,service,address,port,protocol,status) VALUES(gen_random_uuid(),'UDP Multiplayer Position & Telemetry System service','udp','127.0.0.1',0,'UDP','ACTIVE');
INSERT INTO assignments(id,title,description,protocol,difficulty,status,slug,requirements,concepts,metadata) VALUES ('00000000-0000-4000-8000-000000000004','College Student Information API Client','Retrieve and display student records, validating HTTP status before parsing JSON.','HTTP','EASY','ACTIVE','http-api','["GET the configured student path","Parse response JSON","Return name, rollNumber, department and attendance","Handle 4xx and 5xx explicitly"]'::jsonb,'["HTTP","Status codes","REST","JSON"]'::jsonb,'{"objective":"Retrieve and display student records, validating HTTP status before parsing JSON.","constraints":["JavaScript solve(input) runs in an isolated interpreter","15 seconds per test, 16 MiB memory, 60 network operations","Only the supplied LabLink network services are accessible"],"instructions":["Read the protocol and capability API","Implement solve(input) for every test input","Run to inspect output, then Test before submitting"],"expectedBehavior":"http.request(path,''GET'') returns {status,body,latencyMs}. Parse successful body and return all four student fields. Errors return {error:true,status}. Inputs specify path.","starterCode":"function solve(input) {\n  // Implement the requirements using the capability API below.\n  print(input);\n  return {};\n}","serverRequirement":"Controlled HTTP http-api service","capabilityApi":"tcp.connect(''chat''|''file''|''search''|''offline''), tcp.send(id,line), tcp.read(id), tcp.close(id); udp.exchange(updates); http.request(path,method); http.probe(name); dns.lookup(name); save(name,content); sha256(content); print(value). All calls are synchronous inside the isolated interpreter."}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000004','Student record and JSON','http-api',50,'{"input":{"path":"/students/42"}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000004','Not found','http-api',25,'{"input":{"path":"/students/missing"}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000004','Service failure','http-api',25,'{"input":{"path":"/failure"}}'::jsonb);
INSERT INTO network_servers(id,name,service,address,port,protocol,status) VALUES(gen_random_uuid(),'College Student Information API Client service','http','127.0.0.1',0,'HTTP','ACTIVE');
INSERT INTO assignments(id,title,description,protocol,difficulty,status,slug,requirements,concepts,metadata) VALUES ('00000000-0000-4000-8000-000000000005','DNS Troubleshooting Challenge','Investigate why portal.lablink.edu does not open using a controlled DNS resolver and actual reachability checks.','DNS','MEDIUM','ACTIVE','dns-troubleshooting','["Query the affected and working names","Compare DNS answers with endpoint reachability","Record observations, evidence, root cause and recommended fix"]'::jsonb,'["DNS","A records","Resolution","Troubleshooting"]'::jsonb,'{"objective":"Investigate why portal.lablink.edu does not open using a controlled DNS resolver and actual reachability checks.","constraints":["JavaScript solve(input) runs in an isolated interpreter","15 seconds per test, 16 MiB memory, 60 network operations","Only the supplied LabLink network services are accessible"],"instructions":["Read the protocol and capability API","Implement solve(input) for every test input","Run to inspect output, then Test before submitting"],"expectedBehavior":"Use dns.lookup(name) (real UDP DNS query) and http.probe(''portal'' or ''resolved''). The portal A record is deliberately misconfigured. solve(input) returns {observations,dnsInformation,evidence,rootCause,recommendedFix}, with evidence from your calls. Diagnose a wrong A record and recommend correcting it to the reachable address.","starterCode":"function solve(input) {\n  // Query DNS, check reachability, and return your diagnosis with evidence.\n  print(dns.lookup(input.name));\n  return { observations: \"\", dnsInformation: \"\", evidence: \"\", rootCause: \"\", recommendedFix: \"\" };\n}","serverRequirement":"Controlled DNS dns-troubleshooting service","capabilityApi":"tcp.connect(''chat''|''file''|''search''|''offline''), tcp.send(id,line), tcp.read(id), tcp.close(id); udp.exchange(updates); http.request(path,method); http.probe(name); dns.lookup(name); save(name,content); sha256(content); print(value). All calls are synchronous inside the isolated interpreter."}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000005','DNS investigation','dns-troubleshooting',35,'{"input":{"name":"portal.lablink.edu","comparison":"working.lablink.edu"}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000005','Reachability evidence','dns-troubleshooting',30,'{"input":{"name":"portal.lablink.edu","comparison":"working.lablink.edu"}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000005','Diagnosis and repair recommendation','dns-troubleshooting',35,'{"input":{"name":"portal.lablink.edu","comparison":"working.lablink.edu"}}'::jsonb);
INSERT INTO network_servers(id,name,service,address,port,protocol,status) VALUES(gen_random_uuid(),'DNS Troubleshooting Challenge service','dns','127.0.0.1',0,'DNS','ACTIVE');
INSERT INTO assignments(id,title,description,protocol,difficulty,status,slug,requirements,concepts,metadata) VALUES ('00000000-0000-4000-8000-000000000006','Network Monitoring System','Measure configured college services, reporting availability and real elapsed latency.','HTTP','MEDIUM','ACTIVE','network-monitor','["Probe each configured service","Distinguish an HTTP failure, refused connection and timeout","Return availability and measured latency"]'::jsonb,'["Availability","Latency","Timeouts","Monitoring"]'::jsonb,'{"objective":"Measure configured college services, reporting availability and real elapsed latency.","constraints":["JavaScript solve(input) runs in an isolated interpreter","15 seconds per test, 16 MiB memory, 60 network operations","Only the supplied LabLink network services are accessible"],"instructions":["Read the protocol and capability API","Implement solve(input) for every test input","Run to inspect output, then Test before submitting"],"expectedBehavior":"Use http.probe(name), with names lab,file,database,web,slow. Return {servers:[{name,status:''ONLINE''|''OFFLINE'',latencyMs,reason}]}. Classify non-2xx, refusals and timeouts as OFFLINE. timeout input is handled by the capability.","starterCode":"function solve(input) {\n  // Implement the requirements using the capability API below.\n  print(input);\n  return {};\n}","serverRequirement":"Controlled HTTP network-monitor service","capabilityApi":"tcp.connect(''chat''|''file''|''search''|''offline''), tcp.send(id,line), tcp.read(id), tcp.close(id); udp.exchange(updates); http.request(path,method); http.probe(name); dns.lookup(name); save(name,content); sha256(content); print(value). All calls are synchronous inside the isolated interpreter."}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000006','Online endpoints','network-monitor',35,'{"input":{"servers":["lab","file","web"]}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000006','Unavailable database','network-monitor',30,'{"input":{"servers":["lab","database"]}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000006','Timeout handling','network-monitor',35,'{"input":{"servers":["slow","web"]}}'::jsonb);
INSERT INTO network_servers(id,name,service,address,port,protocol,status) VALUES(gen_random_uuid(),'Network Monitoring System service','monitor','127.0.0.1',0,'HTTP','ACTIVE');
INSERT INTO assignments(id,title,description,protocol,difficulty,status,slug,requirements,concepts,metadata) VALUES ('00000000-0000-4000-8000-000000000007','Client-Server File Search','Search a central document server and download a chosen matching file.','TCP','MEDIUM','ACTIVE','file-search','["Send SEARCH <query> and parse matching files","Send GET <selected filename>","Decode and save the file","Handle empty results and invalid selection"]'::jsonb,'["TCP","Request/response","Search","File transfer"]'::jsonb,'{"objective":"Search a central document server and download a chosen matching file.","constraints":["JavaScript solve(input) runs in an isolated interpreter","15 seconds per test, 16 MiB memory, 60 network operations","Only the supplied LabLink network services are accessible"],"instructions":["Read the protocol and capability API","Implement solve(input) for every test input","Run to inspect output, then Test before submitting"],"expectedBehavior":"Connect to search. SEARCH <query> returns a JSON array of filenames. GET <filename> returns JSON {name,content,sha256} or {error:''NOT_FOUND''}. Return {results,name,content,saved:true}; empty results {results:[]}; invalid selection {results,error:true}. save(name,content) records the download.","starterCode":"function solve(input) {\n  // Implement the requirements using the capability API below.\n  print(input);\n  return {};\n}","serverRequirement":"Controlled TCP file-search service","capabilityApi":"tcp.connect(''chat''|''file''|''search''|''offline''), tcp.send(id,line), tcp.read(id), tcp.close(id); udp.exchange(updates); http.request(path,method); http.probe(name); dns.lookup(name); save(name,content); sha256(content); print(value). All calls are synchronous inside the isolated interpreter."}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000007','Search and download','file-search',50,'{"input":{"query":"network","select":"networks.txt"}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000007','No matching documents','file-search',25,'{"input":{"query":"absent","select":null}}'::jsonb);
INSERT INTO assignment_test_cases(id,assignment_id,name,type,weight,configuration) VALUES (gen_random_uuid(),'00000000-0000-4000-8000-000000000007','Invalid selection','file-search',25,'{"input":{"query":"welcome","select":"missing.txt"}}'::jsonb);
INSERT INTO network_servers(id,name,service,address,port,protocol,status) VALUES(gen_random_uuid(),'Client-Server File Search service','search','127.0.0.1',0,'TCP','ACTIVE');

